codemod/commons

msw/2/imports/src/index.ts
msw/2/upgrade-recipe/.codemodrc.json

This PR addresses two issues:  
1. **Bug in `msw/2/imports` Codemod:**  
- Fixed incorrect handling of non-`aliasNode` cases in the `aliasAwareRename` method at line 23.  
- Replaced a deprecated method named `rename` found at line 13 with the correct implementation.  
- Ensured the codemod now executes fully without errors.  
2. **Incorrect Execution Order in `msw/2/upgrade-recipe`:**  
- Adjusted the order of codemod execution for proper functionality.  
- Corrected order:  
- `"msw/2/imports"`  
- `"msw/2/response-usages"`  
- `"msw/2/print-handler"`  
- `"msw/2/lifecycle-events-signature"`  
- `"msw/2/callback-signature"`  
- `"msw/2/type-args"`  
- `"msw/2/request-changes"`  
- `"msw/2/req-passthrough"`  
- `"msw/2/ctx-fetch"`  
These fixes enhance codemod reliability and streamline …

fix: fix msw/2/imports codemod bug for aliasAwareRename and msw/2/upgrade-recipe bug in order of run codemods

---

codemods/react/create-element-to-jsx/cdmd_dist/index.js
codemods/react/create-element-to-jsx/src/index.js

This PR moves the CommonJS (CJS) distribution and source files to JavaScript files in the `create-element-to-jsx` codemod. This change ensures compatibility and makes the codemod easier to use and integrate.
The changes were tested by running the `create-element-to-jsx` codemod to ensure the CJS files are correctly moved and function properly as JavaScript files. No issues were found during testing.

fix(codemods/react/create-element-to-jsx): move CJS dist file and CJS source file to JS file in create-element-to-jsx codemod

---

codemods/react/update-react-imports/__testfixtures__/satisfies-import.input.tsx
codemods/react/update-react-imports/__testfixtures__/satisfies-import.output.tsx
codemods/react/update-react-imports/__testfixtures__/satisfies2-import.input.tsx
codemods/react/update-react-imports/__testfixtures__/satisfies2-import.output.tsx
codemods/react/update-react-imports/test/test.ts

Previously, the issue of TypeScript support was addressed in this PR: [#9](https://github.com/codemod-com/commons/pull/9), which resolved problems related to detecting imports like `* as React`, adding support for TypeScript structures, and fixing `MouseEvent` handling.
In this PR, I added additional test cases specifically to test files that include the `satisfies` keyword. These tests aim to ensure that the `update-react-imports` codemod works as expected when handling TSX files containing `satisfies`. This ensures compatibility with more advanced TypeScript features and strengthens overall reliability.  
Fixes [#324](https://github.com/reactjs/react-codemod/issues/324)
- Added the following test cases:
- A TSX file using the `satisfies` keyword to validate that imports are updated …

feat(codemods/react/update-react-imports): add two test cases for TypeScript TSX files using 'satisfies'

---

codemods/typescript/remove-public-modifier/src/index.ts
codemods/typescript/remove-public-modifier/test/test.ts

This is https://github.com/codemod-com/codemod/pull/1414 for the right repository.
Only remove public modifier, keep
any private/protected modifiers.
No issue.
Not sure, I get a lot of failures with `pnpm recursive run test` in the node:20 docker container. 
Test passed in the PR for the other repository.
Bug fix, no functional change compared to the documentation.

fix: typescript/remove-public-modifier: keep private/protected

---

.github/workflows/main.yaml

📚 Description
This PR addresses an issue where the actions/setup-node@v4 step in our GitHub Actions workflow was using the pnpm cache, causing failures due to the absence of a lock file. To resolve this, I have removed the pnpm cache from the setup step to ensure smoother execution.
🔗 Linked Issue
Fixes [#17](https://github.com/codemod-com/commons/issues/17) - CI fails for main branch.
🧪 Test Plan
I tested the changes by running the GitHub Actions workflow. After removing the pnpm cache, the workflow ran successfully without issues.
📄 Documentation to Update
No documentation changes are required as this is a bug fix with no functional changes to the overall system.

fix(GHA): remove PNPM cache in setup-node action

---

.github/workflows/publish.yaml

This PR addresses the following changes in the `publish` GitHub Action:
- Fixed the `pnpm` version to ensure compatibility and consistency across environments.
- Remove the used `test` step from the `main` step **temporary**
These improvements help streamline the CI process.
- Verified that the `pnpm` version used is correct and consistent during the CI process.
- Tested the `publish` GitHub Action to ensure that the removal of the redundant test step did not impact the publishing flow.

fix: fix the pnpm version and remove used test step for main test

---

.github/workflows/publish.yaml

Added `workflow_dispatch` event to the publishing workflow, enabling manual triggering of the workflow when needed.  
This enhances flexibility by allowing users to publish changes outside of the predefined triggers.
- Verified the workflow dispatch functionality by triggering the workflow manually in a forked repository.  
- Confirmed that the workflow runs successfully and is complete as expected.

feat: add workflow dispatch event to publish workflow

---

codemods/react/19/replace-default-props/.codemodrc.json
codemods/react/19/replace-default-props/__testfixtures__/button-jsx-example-input.jsx
codemods/react/19/replace-default-props/__testfixtures__/button-jsx-example-output.jsx
codemods/react/19/replace-default-props/__testfixtures__/nested-destructuring.output.tsx
codemods/react/19/replace-default-props/__testfixtures__/with-functions.output.tsx
codemods/react/19/replace-default-props/src/index.ts
codemods/react/19/replace-default-props/test/test.ts

This PR fixes the `react/19/replace-default-props` codemod to properly handle:
1. JSX files (previously unsupported).
2. Identifying and processing `Property` nodes with `jscodeshift` to ensure default props are correctly added to destructured component props.
The issue caused the codemod to remove `defaultProps` without adding default values to destructured component props. This bug has been resolved with the changes introduced.
Codemod Issue: [#1400](https://github.com/codemod-com/codemod/issues/1400)
React-codemod Issue: [#321](https://github.com/reactjs/react-codemod/issues/321)
Tests were performed with the following scenarios:
**JSX and TSX files**:
- Verified the codemod converts `defaultProps` to default destructured values.
- Tested multiple edge cases with different prop types …

fix(codemods/react/19/replace-default-props): fix support for JSX files and Property jscodeshift type in react/19/replace-default-props codemod

---

.github/workflows/publish.yaml

This PR fixes two critical issues in the publish workflow:
1. **Bug in `paths-filter` job output:** The paths-filter job was not providing the correct output, which caused downstream steps to fail.  
2. **Error handling in Codemod Publish:** When the `codemod publish` step encountered an error, it was not handled properly, leading to the workflow's failure.
These fixes improve the robustness and reliability of the publish workflow.
1. Triggered the publish workflow with multiple scenarios:
- Successful paths-filter output.
- Failure in the `codemod publish` step.
2. Verified that the workflow completes as expected in both cases:
- Proper outputs are passed between jobs.
- Errors in the `codemod publish` step are handled gracefully.

fix(workflow/publish): resolve issues in paths-filter output and codemod publish error in workflow handling

---

tooling/workflow/package.json

This PR removes the `test` script from the `package.json` file in the `tooling/workflow` directory. The script was unnecessary, and its removal ensures a cleaner and more accurate package configuration.
---
1. Verify that the `test` script has been removed from the `package.json` file.  
2. Confirm all workflows and processes function correctly without the `test` script.

fix(tooling/workflow): remove test script from package.json in workflow

---

package.json
vitest.config.ts

This PR addresses an issue where codemods without a dedicated `vitest.config` file were failing tests. The solution ensures that such codemods default to using the `vitest.config` file from the workspace, preventing unnecessary test failures and improving compatibility.
---
1. Run tests for codemods without their own `vitest.config` file:  
```bash
pnpm recursive run test
```
2. Verify that the workspace `vitest.config` file is used correctly.
3. Confirm all tests pass successfully across affected codemods.

fix: resolve test failures for codemods missing vitest.config file

---

codemods/webpack/v5/json-imports-to-default-imports/__testfixtures__/fixture1.output.ts
codemods/webpack/v5/json-imports-to-default-imports/__testfixtures__/fixture2.output.ts
codemods/webpack/v5/json-imports-to-default-imports/__testfixtures__/fixture3.output.ts

This PR fixes issues with the test fixtures for the `webpack/v5/json-imports-to-default-imports` codemod. The previous fixtures had incorrect data, which caused test failures and inconsistent results. This update ensures that the test fixtures are accurate and aligned with the expected codemod behavior.
---
1. Run all tests using the updated fixtures:  
```bash
npm run test
```
2. Confirm all tests pass successfully.
3. Manually verify that the updated fixtures represent the intended transformations.

fix(codemods/webpack/v5/json-imports-to-default-imports): correct test fixtures for the codemod 

---

codemods/webpack/v5/migrate-library-target-to-library-object/__testfixtures__/fixture1.output.ts
codemods/webpack/v5/migrate-library-target-to-library-object/__testfixtures__/fixture2.output.ts
codemods/webpack/v5/migrate-library-target-to-library-object/__testfixtures__/fixture3.output.ts
codemods/webpack/v5/migrate-library-target-to-library-object/__testfixtures__/fixture4.output.ts

This PR fixes issues with the test fixtures for the `webpack/v5/migrate-library-target-to-library-object` codemod. The previous fixtures had incorrect data, which caused test failures and inconsistent results. This update ensures the test fixtures are accurate and aligned with the expected codemod behavior.
---
1. Run all tests using the updated fixtures:  
```bash
npm run test
```
2. Confirm all tests pass successfully.
3. Manually verify that the updated fixtures represent the intended transformations.

fix(codemods/webpack/v5/migrate-library-target-to-library-object): correct test fixtures for the codemod

---

codemods/netlify-sdk/0.8.5/deleteEnvironmentVariable/package.json

This PR removes the `test` script from the `package.json` file in the `deleteEnvironmentVariable` codemod under `netlify-sdk/0.8.5`. The script was unnecessary, and its removal ensured a cleaner configuration for the codemod.
---
1. Verify that the `test` script has been removed from the `package.json` file.  
2. Ensure all related processes or workflows are unaffected by the removal.

fix(codemods/netlify-sdk/0.8.5/deleteEnvironmentVariable): remove test script from package.json in deleteEnvironmentVariable codemod

---

tooling/utilities/package.json

This PR removes the `test` script from the `package.json` file in the `@codemod.com/codemod-utils` tool. The script was unnecessary, and its removal ensures a cleaner and more accurate package configuration.
---
1. Verify that the `package.json` file no longer includes the `test` script.  
2. Confirm that all related workflows or processes function as expected without the script.

fix: remove test script from package.json in @codemod.com/codemod-utils

---

codemods/react/create-element-to-jsx/test/test.ts

This PR fixes an issue with the transform import path in the test file for the `create-element-to-jsx` codemod in the `react` category. The incorrect path caused test failures and inconsistencies during execution. The updated import path ensures the tests function correctly and reference the intended module.
---
1. Run the tests for the `create-element-to-jsx` codemod:  
```bash
npm test
```
2. Confirm that all tests pass without errors.
3. Verify that the import path in the test file now correctly references the target module.

fix(codemods/react/create-element-to-jsx): correct transform import path in create-element-to-jsx test file

---

codemods/react/19/remove-legacy-context/__testfixtures__/class-component.output.tsx
codemods/react/19/remove-legacy-context/package.json
codemods/react/19/remove-legacy-context/src/index.ts

This PR fixes multiple issues related to the `remove-legacy-context` codemod in the `react/19` directory. The following changes were made:
1. **Fix the main codemod logic**: Resolved functional issues in the `remove-legacy-context` codemod to ensure accurate transformation.  
2. **Fix test fixtures**: Corrected and updated test fixtures to align with the codemod's expected behavior.  
3. **Handle null cases in `findPatterns`**: Fixed a bug where `findPatterns` could return null, causing runtime errors during execution.  
4. **Correct package address**: Updated the `@codemod.com/codemod-utils` package address to the correct location in `remove-legacy-context`.  
---
1. Run tests for the `remove-legacy-context` codemod:  
```bash
npm test
```
2. Validate the updated fixtures to confirm …

fix(codemods/react/19/remove-legacy-context): improve and fix issues in remove-legacy-context codemod

---

.gitignore
pnpm-lock.yaml

This PR updates the `.gitignore` file by removing `pnpm-lock.yaml`, `yarn.lock`, and `package-lock.json` from the ignored files. Additionally, it includes the `pnpm-lock.yaml` file in version control to ensure consistency across package installations.
- Verified that `pnpm-lock.yaml` is now tracked by Git.
- Confirmed that unnecessary lock files are no longer ignored.

chore: update .gitignore and add pnpm lock file

---

codemods/react/prop-types-typescript/.codemodrc.json
codemods/react/prop-types-typescript/package.json
codemods/react/prop-types-typescript/src/index.ts

This refactors the `prop-types-typescript` codemod source by replacing `@ts-expect-error` comments with explicit `any` type annotations. This change makes type assignments more explicit, reducing reliance on suppression comments while maintaining functionality.  
- Run `npm run test` to verify that the codemod works correctly.

refactor(codemods/react/prop-types-typescript): replace @ts-expect-error with explicit any annotations

---

.husky/pre-commit
biome.json
package.json

This PR configures **Husky** and **biomejs** to automate code formatting in the repository. Husky ensures that biomjs run before each commit, helping maintain code quality and consistency across the project.
Key changes include:
- Setting up Husky hooks to run `biomejs` on staged files.
- Installing **biomejs** and integrating it for additional code formatting.
1. Make changes to any file in the repository.
2. Stage the changes with `git add .`.
3. Commit the changes with `git commit -m 'test commit'`.
4. Verify that `biomejs` automatically format the staged files.

feat: configure Husky and biomejs for automated code formatting

---

codemods/react/19/replace-default-props/.codemodrc.json
codemods/react/19/replace-default-props/__testfixtures__/implicit-return.input.jsx
codemods/react/19/replace-default-props/__testfixtures__/implicit-return.output.jsx
codemods/react/19/replace-default-props/src/index.ts
codemods/react/19/replace-default-props/test/test.ts

This update makes the replace-default-props work with functional components that are defined using arrow function with implicit return.
https://github.com/codemod-com/commons/issues/65
Added test case for the implicit-return functional component. Made sure other tests still pass.
There shouldn't be any additional updates required for codemod to work for the described case.

feat(replace-default-props): make it work for function components with implicit return
